---

- name: Setup package repo
  include_tasks: setup.yml

- name: Install Filebeat.
  package: name=filebeat state=present

- include_tasks: config.yml
  when: filebeat_create_config

- name: Ensure Filebeat is started and enabled at boot.
  service:
    name: filebeat
    state: started
    enabled: true
